# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=200)),
                ('Short_Description', models.TextField()),
                ('Header_Image', models.TextField()),
                ('SteamUrl', models.TextField()),
                ('Publishers', models.TextField()),
                ('Release_Date', models.DateField()),
            ],
        ),
    ]
